### PR TITLE
Allow visitors to listen if they have no mic

### PR DESCRIPTION
**Pull request by chromakode**
This is a quick version to get this working without UI -- in the future, we should indicate that a microphone could not be found.

While testing this, one issue I noticed is that when I join the room without a mic, only peers that connected _after_ me were visible. In contrast, when I joined with a mic, pre-existing peers seemed to be loaded as expected. Could this be a consequence of not sending a stream along? I'm suspecting that a peer list might be sent down once you emit data?

### CODE REVIEW

**Comment by mikeal** [comment]
Can we get some UI on the receiver's end that says this person _chose_ not to give their mic input? We still run into bugs sometimes where we can't get the audio to work and I worry about this confusing the debugging for that.

**Comment by chromakode** [comment]
Sure will do. I'm in the process of updating this to catch up to today's master changes. Will add some UI as well.

**Comment by chromakode** [comment]
Done! Here's what it looks like when connecting without a mic:

image

In the future I'd like to include some instructions on how to troubleshoot missing input/denied privs, but for now just putting a simple message to clarify why no audio is being sent.

I've also updated the implementation so that you still get a user card and can play audio files on disk.

**Comment by mikeal** [comment]
We also need to leave these peers out of the recording process.

Best thing to do is probably to just opt out of the entire `recording()` function which sets up the RPC and local recording. If the listen-only peer never sets up the RPC calls for recording it won't ever be called to record by any of the remote peers.

That's the last thing I think we need before merged.

At some point down the line we should add some kind of display UI that shows how many people are listening in but not participating.

**Comment by chromakode** [comment]
I initially took the peers out of the recording process in the 2nd commit, but put it back in because I realized that a user without a mic could be playing an audio file, which should be included in the recording. Is there a better way to handle this edge case?

**Comment by mikeal** [comment]
@chromakode oh wow, good point.

Actually, I'm realizing that with the way we are doing the outbound audio (as of yesterday when I moved to the new version of `waudio`) we can enter rooms before getting mic access.

This has some bigger repercussions than I had realized.
- The initialization process can be changed to do both (getting rtcConfig and entering room) and (asking for mic input) in parallel.
- The loading of people into the room and other UI no longer needs to block on mic access, we append the text you have here about not being approved yet until permission is granted (if ever).

/cc @FotoVerite and @vladaspasic

**Comment by chromakode** [comment]
@mikeal Could we please merge this and then proceed with those improvements? It's been tricky maintaining this branch against master since it's changing so fast. It looks like it's got conflicts again -- I'll work on resolving those now.

**Comment by chromakode** [comment]
Rebased!

**Comment by vladaspasic** [comment]
I think as well that the `joinRoom` function needs some refactoring. My suggestion is to create a simple class that extends `EventEmitter` that would handle the mic permissions, getting config, joining the room.
It would proxy the events like `stream` and `disconnect` from `swarm`, but we should add couple of events that would be used to update the UI.

I would start by adding a loading indicator in the room page, [example](http://semantic-ui.com/elements/loader.html), and wait for these events to update the UI:
- `connected` when user joins the room. Removes the loading indicator
- `audio` when `audioStream` is available. Create a outbound audio and join the room, add recording button, I guess :)
- `blocked` when user denies access to Mic. Show the UI warning that the user needs to grant us permissions
- `unavailable` when user has no Mic. Show the UI warning that the user can only be a silent listener
- `error` Any other kind of error. Show some sad face :)

**Comment by mikeal** [comment]
> Could we please merge this and then proceed with those improvements?

Sure, but it needs to be rebased again first :(

> I think as well that the joinRoom function needs some refactoring. My suggestion is to create a simple class that extends EventEmitter

Agree that it needs some refactoring but I don't know if making it a class is the best route.

> connected when user joins the room. Removes the loading indicator

We actually don't have any underlying state that corresponds to "entered" the room. The states are essentially:
- Ask `room-exchange` for a list of all public keys that have been in the room.
- Attempt to connect to all known peers via `signal-exchange`.
  - We don't know if these peers are still alive until we attempt to connect.
- Upon connecting to _any_ peer we get a list of public keys that peer is connected to.
  - Any peer we aren't already connected/connecting to that this peer is already connected to we attempt to connect to those peers by having this intermediate peer proxy the signals.

Every new peer goes through the same process, at any time, so we never know if we are _entirely_ connected to the swarm because it changes over time.

> audio when audioStream is available. Create a outbound audio and join the room, add recording button, I guess :)

We can actually enter the room now _before_ we get the microphone. Once we get the microphone we just `connect()` it to the `waudio` instance we already used when creating the swarm instance (which is what we do to enter the room).

**Comment by chromakode** [comment]
Ok, updated! This change is now pretty small. It just replaces the fatal no mic access messages at start with allowing the user to enter the room and displaying the notice that they're "listening only" at the top.

**Comment by vladaspasic** [comment]
OK, then `connected` is maybe a bad name for it, what I meant is this event would be fired when rtcConfig is obtained, we could rename to `ready` or something similar.

Regarding the `audio` event, this is what I also meant. Execute 2 things in parallel:
- fetch the rtcConfig and create the swarm
- get Media devices, check if granted and available and connect to the swarm

We should look out after race conditions in these cases.

Anyway, these events are mainly used to update the UI state. This was the mean reason why I wanted to use a class, and it would make the code a lot cleaner.

``` javascript
const room = new Room(roomNumber);
room.on('stream', (stream) => addNewStream(stream, room))
room.on('disconnect', (key) => disconnect(key))
room.on('ready', () => removeLoading())
room.on('audio', () => addRecordingButton())
room.on('blocked', () => showWarning())
...
```

**Pull request merged**
