### PR TITLE
Created persistent settings

### PR DESCRIPTION
**Pull request by vladaspasic**
Hi, 

with these changes users can now store their names and modify their input device, as requested in #12 . When input device is changed, the current `audioStream` will remain unchanged. Only when user reloads the page, his preferred(stored) device would be selected. We should maybe think how to implement the audio stream switch when user updates his settings. 

Added a modal window when user drags a file across the page. Maybe not the best UI solution, but there should be more hints and instructions for users on how to use the app.

I also moved some of the code, that was related to UI, to a new `lib/views` folder.  I think it would be best to split the code a bit so it would be easier to maintain and read.

### CODE REVIEW

**Comment by mikeal** [comment]
This includes a lot of style changes that aren't in line with `standard`. I just pushed a change to get standard into `npm test`.

I like that the views are in a different file but I wonder if it's a bit of overkill to have each view in its own file, might want to just stick them all in one file for now.

**Comment by vladaspasic** [comment]
OK, I will revert the changes made to the code, so that they would comply with `standard` checkstyle and merge the views into one file.

**Comment by vladaspasic** [comment]
I have pushed changes that would fix code style issues and merged views into one file.

**Comment by mikeal** [comment]
It says there are still conflicts but I'm going to pull down this branch locally for review, it's a big change but from what I can see in the diff it looks pretty great.

**Comment by vladaspasic** [comment]
Just added the fixed `bundle.js`, it would still show conflicts though.

**Comment by mikeal** [comment]
I've got it pulled down locally and it's working great, I just don't know if the placement of the button is right.

screen shot 2016-10-15 at 2 42 59 pm

It overlays the call UI. Maybe we should reduce the button to just the icon and sit it to the left of the record button?

**Comment by vladaspasic** [comment]
It is where it should it be, as it is positioned absolute. I will add a fix for it. Maybe creating a menu element, that could be absolute, that would contain all the buttons.

**Comment by mikeal** [comment]
I made a couple UI tweaks and fixed some merge conflicts and then committed it :)

screen shot 2016-10-15 at 2 54 46 pm

**Comment by mikeal** [comment]
BTW, the title and description here don't really do this PR justice :) You also added the drag and drop modal and did a ton of general cleanup as well as a proper input selection, this is great!!

**Comment by mikeal** [comment]
I was so excited about this patch that I purged the Cloudflare cache so that we could see it live right away :)

**Comment by vladaspasic** [comment]
That is great! Glad I could help

**Comment by chromakode** [comment]
:clap: Awesome work!

**Pull request merged**
