### PR TITLE
Use circle icon for record button

### PR DESCRIPTION
**Pull request by chromakode**
image

### CODE REVIEW

**Comment by FotoVerite** [comment]
I'll add css animations to make it blink when recording.

**Comment by chromakode** [comment]
@FotoVerite could you please turn it red as well?

**Comment by FotoVerite** [comment]
I thought that was obvious. 💃

**Comment by mikeal** [comment]
I'm a little confused about the state of this. Should we merge it and then expect a PR from @FotoVerite for colors or are we waiting for a new PR with the colors already in it? 

I'm fine either way, just wanna know if we should merge or close this PR :)

**Comment by chromakode** [comment]
Let's land this since it's finished and won't block future improvements.

**Pull request merged**
