### PR TITLE
Post autobuild updates

### PR DESCRIPTION
**Pull request by chromakode**
- :scissors: manual bundle
- :sparkles: add staging link to readme

### CODE REVIEW

**Comment by mikeal** [comment]
Bah, the removal of bundle.js is in conflict now. Would love to get this updated and checked in.

**Comment by chromakode** [comment]
@mikeal Does it still conflict? The pull request page indicates it as ready to merge.

**Comment by mikeal** [comment]
It got fixed when I merged another PR that deleted the bundle :)

**Comment by vladaspasic** [comment]
@chromakode can you add the `worker.js` file in the `copy_assets` function on the build script?
As this caused this issue #87

**Comment by chromakode** [comment]
@vladaspasic Aha! Sorry about that. Could you please whip up a PR?

**Pull request merged**
