### PR TITLE
Change to the UI Entering App

### PR DESCRIPTION
**Pull request by pertrai1**
roll_call

### CODE REVIEW

**Comment by mikeal** [comment]
I'm interested in what people think about using a Modal rather than the two buttons we have now.

The two buttons we have right now are definitely confusing, but I'm curious what other people's ideas are for the front page.

I'm +1 on breaking the CSS into its own file but while it's just one file let's stick it in the root.

**Comment by mikeal** [comment]
Pinging @chromakode and @FotoVerite to see what they think.

**Comment by FotoVerite** [comment]
different icon for create a new room. Audio makes no sense. We also should have editable field for create a new room for the name. and a go button. We could prepopulate it with a nonsense word much like github does for repos. Eventually we should also have a way to clip the url for easy invite but that's hard ux.

**Comment by mikeal** [comment]
ya, the "create room" UI should be setable and pre-populated with a randomly generated room.

**Comment by mikeal** [comment]
After thinking about this a bit more, our current UI is pretty new user hostile.

The page does nothing to explain what Roll Call is or what it can be used for. Even something as simple as explaining that it is open source and contributions are welcome is missing.

I'd be +1 on a page that had a lot more introductory text. Maybe we can keep the two options (join party and create room) but right below them I think it would be good to have a lot more text to help people just finding the page understand what it is.

**Comment by pertrai1** [comment]
👍  on more thought into the UI with low res wireframe to iterate with. I am going to close this PR and discussion can continue in an enhancement issue.

**Pull request closed without merging**
