### PR TITLE
Added UI messages for error and loading states

### PR DESCRIPTION
**Pull request by vladaspasic**

### CODE REVIEW

**Comment by mikeal** [comment]
LGTM. We're good to go once the merge conflicts are fixed.

**Comment by vladaspasic** [comment]
Conflicts are fixed and the check for MediaRecorder support is added.

**Comment by vladaspasic** [comment]
There was a bug in the code, it would throw an error always. I will provide a hotfix on master directly.

**Comment by mikeal** [comment]
Ok, let me know when it lands and I'll have Cloudflare flush the cache.

**Comment by chromakode** [comment]
Ah, I opened https://github.com/mikeal/roll-call/pull/49 about this. Closing in favor of your fix, @vladaspasic

**Comment by vladaspasic** [comment]
Done

**Comment by mikeal** [comment]
Flushing the cache :)

**Comment by vladaspasic** [comment]
Sorry about this, it is getting late here :)

**Pull request merged**
